version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy
          command: ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: AEWEB
